#!/bin/bash
echo "using <ssh -N -D 0.0.0.0:1080 localhost > to make local proxy for socks5"
folder='/tmp/ovpnconf/tmp/ovpn/'
rm -rf $folder/*
python /home/sick/vg_midser/midser/client/main.py
trap "break" 3
trap "continue" 2


#for tempvar in `ls /home/john/VPN/*KR*.ovpn /home/john/VPN/*JP*.ovpn | sort -nr -k 2 -t "k"`
for tempvar in `ls "$folder"Japan*.ovpn | sort -nr -k 2 -t "k"`
do

sudo openvpn --cipher CBC --tls-client --float --allow-pull-fqdn --redirect-gateway --auth-nocache --inactive 20 --ping 3 --ping-exit 21 --tls-exit --config $tempvar
#sudo openvpn --cipher CBC --tls-client --float --allow-pull-fqdn --redirect-gateway --auth-nocache --inactive 10 --ping 3 --ping-exit 21 --remote-cert-tls server --tls-exit --config $tempvar
#sudo openvpn --cipher CBC --tls-client --float --allow-pull-fqdn --redirect-gateway --auth-nocache --inactive 35 --ping 2 --ping-exit 21 --config $tempvar

#mv $tempvar /home/john/VPN/bk

done

#sudo openvpn --allow-pull-fqdn --redirect-gateway --auth-nocache --config $1 
#sudo openvpn --allow-pull-fqdn --redirect-gateway --auth-nocache --remote-cert-tls server --config $1 
#--inactive 10
